//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.18051
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class settings {
    
    private settingsTimefile timefileField;
    
    private settingsTemperature temperatureField;
    
    private settingsLevel[] startlevelsField;
    
    private settingsExecution executionField;
    
    /// <remarks/>
    public settingsTimefile timefile {
        get {
            return this.timefileField;
        }
        set {
            this.timefileField = value;
        }
    }
    
    /// <remarks/>
    public settingsTemperature temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("level", IsNullable=false)]
    public settingsLevel[] startlevels {
        get {
            return this.startlevelsField;
        }
        set {
            this.startlevelsField = value;
        }
    }
    
    /// <remarks/>
    public settingsExecution execution {
        get {
            return this.executionField;
        }
        set {
            this.executionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsTimefile {
    
    private string methodField;
    
    private string pathField;
    
    private settingsTimefileReadinterval readintervalField;
    
    /// <remarks/>
    public string method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    public settingsTimefileReadinterval readinterval {
        get {
            return this.readintervalField;
        }
        set {
            this.readintervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsTimefileReadinterval {
    
    private byte hoursField;
    
    private byte minutesField;
    
    private byte secondsField;
    
    /// <remarks/>
    public byte hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    public byte minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    public byte seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsTemperature {
    
    private string methodField;
    
    private string pathField;
    
    private settingsTemperatureReadinterval readintervalField;
    
    /// <remarks/>
    public string method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    public settingsTemperatureReadinterval readinterval {
        get {
            return this.readintervalField;
        }
        set {
            this.readintervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsTemperatureReadinterval {
    
    private byte hoursField;
    
    private byte minutesField;
    
    private byte secondsField;
    
    /// <remarks/>
    public byte hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    public byte minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    public byte seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsLevel {
    
    private sbyte temperatureField;
    
    private byte hoursField;
    
    private byte minutesField;
    
    private byte secondsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsExecution {
    
    private string executableField;
    
    private settingsExecutionFlags flagsField;
    
    private settingsExecutionDelayShutdown delayShutdownField;
    
    /// <remarks/>
    public string executable {
        get {
            return this.executableField;
        }
        set {
            this.executableField = value;
        }
    }
    
    /// <remarks/>
    public settingsExecutionFlags flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
    
    /// <remarks/>
    public settingsExecutionDelayShutdown delayShutdown {
        get {
            return this.delayShutdownField;
        }
        set {
            this.delayShutdownField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsExecutionFlags {
    
    private string onField;
    
    private string offField;
    
    /// <remarks/>
    public string on {
        get {
            return this.onField;
        }
        set {
            this.onField = value;
        }
    }
    
    /// <remarks/>
    public string off {
        get {
            return this.offField;
        }
        set {
            this.offField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class settingsExecutionDelayShutdown {
    
    private byte hoursField;
    
    private byte minutesField;
    
    private byte secondsField;
    
    /// <remarks/>
    public byte hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    public byte minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    public byte seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
}
